apiVersion: v1
kind: Service
metadata:
  name: chirpstack-ns
  labels:
    app: chirpstack-ns
spec:
  ports:
    - port: 8000
      name: chirpstack-ns
  type: ClusterIP
  selector:
    app: chirpstack-ns
