apiVersion: apps/v1
kind: Deployment
metadata:
  name: chirpstack-as
  labels:
spec:
  selector:
    matchLabels:
      app: chirpstack-as
  replicas: 1
  template:
    metadata:
      labels:
        app: chirpstack-as
    spec:
      containers:
      - name: chirpstack-as
        image: chirpstack/chirpstack-application-server:3
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: configfile
          mountPath: /etc/chirpstack-application-server
        ports:
        - name: chirpstack-as
          containerPort: 8080
      volumes:
      - name: configfile
        configMap:
          name:  chirpstack-as-configmap