apiVersion: v1
kind: ConfigMap
metadata:
  name: chirpstack-as-configmap
data:
  chirpstack-application-server.toml: |
    # See https://www.chirpstack.io/application-server/install/config/ for a full
    # configuration example and documentation.

    [postgresql]
    dsn="postgres://chirpstack_as:chirpstack_as@pgsql.default.svc.cluster.local/chirpstack_as?sslmode=disable"

    [redis]
    url="redis://redis.default:6379"

    [application_server.integration.mqtt]
    server="tcp://mosquitto.default:1883"

    [application_server.api]
    public_host="chirpstack-as.default:8001"

    [metrics]
    timezone="Local"

      [metrics.redis]
      aggregation_intervals=["MINUTE", "HOUR", "DAY", "MONTH"]

      minute_aggregation_ttl="2h0m0s"
      hour_aggregation_ttl="48h0m0s"
      day_aggregation_ttl="2160h0m0s"
      month_aggregation_ttl="17520h0m0s"

      [metrics.prometheus]
      endpoint_enabled=true
      bind="0.0.0.0:22981"
      api_timing_histogram=true

    [application_server.external_api]
    bind="0.0.0.0:8080"
    jwt_secret="verysecret"
