#ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chirpstack-{{studid}}
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - host: chirpstack-{{studid}}.9c06d1e5623147539108.eastus.aksapp.io
      http:
        paths:
          - backend: # How the ingress will handle the requests
              service:
               name: chirpstack-{{studid}} # Which service the request will be forwarded to
               port:
                 name: chirpstack-as # Which port in that service
            path: / # Which path is this rule referring to
            pathType: Prefix # See more at https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types