apiVersion: v1
kind: Service
metadata:
  name: newland
  labels:
   app: newland
spec:
  ports:
    - port: 8080
      name: chirpstack-as
    - port: 8001
      name: chirpstack-as-8001
    - port: 8003
      name: chirpstack-as-join
  type: LoadBalancer
  selector:
    app: newland
    # {{- include "chirpstack.matchLabels" . | nindent 4 }}