apiVersion: apps/v1
kind: Deployment
metadata:
  name: chirpstack-redis-exporter
spec:
  selector:
    matchLabels:
      app: redis-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
      - name: redis-exporter
        image: oliver006/redis_exporter:v1.14.0
        imagePullPolicy: IfNotPresent
        env:
        - name: redishost
          value: redis