apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chirpstack-redis1
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 30 #default 30
      containers:
      - name: redis
        image: redis:6.0.9
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis-pvc
          mountPath: /data
          subPath: redis
      volumes:
      - name: redis-pvc
        persistentVolumeClaim:
          claimName: chirpstack-redis

