
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-bridge
spec:
  selector:
    matchLabels:
      app: gateway-bridge
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-bridge
    spec:
      containers:
      - name: gateway-bridge
        image: chirpstack/chirpstack-gateway-bridge:3
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: configfile
          mountPath: /etc/chirpstack-gateway-bridge
      volumes:
      - name: configfile
        configMap:
          name:  chirpstack-gb-configmap
          