
apiVersion: v1
kind: Service
metadata:
  name: gateway-bridge
  labels:
    app: gateway-bridge
spec:
  ports:
    - port: 1700
      name: gateway-bridge
      protocol: UDP
  type: ClusterIP
  selector:
    app: gateway-bridge
    
